"""Read and validate branding.yaml: everything personal in the report comes from here.

A fork only has to edit branding.yaml. A mistake in it (e.g. a misspelt category)
is reported by `python manage.py check` before the site starts, not as a broken
report in front of a client.
"""

from datetime import date
from functools import lru_cache
from pathlib import Path

import yaml
from django.conf import settings
from pydantic import BaseModel, Field, HttpUrl

from bizzcheckup.engine.types import Category


class Service(BaseModel):
    name: str
    description: str
    related_categories: list[Category] = Field(min_length=1)


class Legal(BaseModel):
    """Details the legal pages need: who runs the service and under which law."""

    operator: str
    country: str
    updated: date


class CallToAction(BaseModel):
    heading: str
    text: str
    button_label: str
    button_url: HttpUrl


class Branding(BaseModel):
    product_name: str = "BizzCheckup"
    tagline: str = "Check your business's online health"
    report_title: str = "BizzCheckup Health Report"
    footer_note: str = "Generated by BizzCheckup — Check your business's online health"

    name: str
    title: str
    photo_url: HttpUrl | None = None
    intro: str = ""
    highlights: list[str] = Field(default_factory=list)

    email: str
    whatsapp_url: HttpUrl | None = None
    website: HttpUrl | None = None
    github: HttpUrl | None = None
    cv_url: HttpUrl | None = None
    portfolio_url: HttpUrl | None = None
    qr_target: HttpUrl | None = None

    services: list[Service] = Field(default_factory=list)
    call_to_action: CallToAction
    legal: Legal

    @property
    def first_name(self) -> str:
        return self.name.split()[0] if self.name else ""

    def services_for(self, category: Category) -> list[Service]:
        """Services that treat this category, most specific (fewest categories) first."""
        matching = [s for s in self.services if category in s.related_categories]
        return sorted(matching, key=lambda service: len(service.related_categories))


def read_branding(path: Path) -> Branding:
    with path.open(encoding="utf-8") as file:
        data = yaml.safe_load(file)  # safe_load: never runs code hidden in the file
    return Branding.model_validate(data or {})


@lru_cache(maxsize=1)
def _cached(path: str, modified: float) -> Branding:
    return read_branding(Path(path))


def load_branding() -> Branding:
    """The current branding. Re-read automatically when the file changes."""
    path = Path(settings.BRANDING_FILE)
    return _cached(str(path), path.stat().st_mtime)
