# Generated by Django 5.2.18 on 2026-10-07 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_step', models.CharField(default='Waiting to start', max_length=100)),
                ('score_performance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_accessibility', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_best_practices', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_seo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_agentic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('health_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_results', models.JSONField(blank=True, default=dict)),
                ('screenshot', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkups', to='checkups.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('accessibility', 'Accessibility'), ('best_practices', 'Best practices'), ('seo', 'Seo'), ('agentic', 'Agentic')], max_length=20)),
                ('severity', models.CharField(choices=[('pass', 'Pass'), ('info', 'Info'), ('warn', 'Warn'), ('fail', 'Fail')], max_length=10)),
                ('message', models.TextField()),
                ('why_it_matters', models.TextField()),
                ('how_to_fix', models.TextField()),
                ('effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('affected_urls', models.JSONField(blank=True, default=list)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='checkups.checkup')),
            ],
            options={
                'ordering': ['checkup', 'category', 'check_id'],
                'indexes': [models.Index(fields=['checkup', 'category'], name='finding_category_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='checkup',
            index=models.Index(fields=['url', 'status', 'created_at'], name='checkup_reuse_idx'),
        ),
        migrations.AddIndex(
            model_name='checkup',
            index=models.Index(fields=['ip_hash', 'created_at'], name='checkup_ip_idx'),
        ),
    ]
