# Generated by Django 5.2.18 on 2026-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
