# Generated by Django 5.2.18 on 2026-10-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkups', '0002_checkup_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='snippets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
