# Generated by Django 5.2.18 on 2026-10-08 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkups', '0003_finding_snippets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('link_preview', 'Link preview picture'), ('mobile', 'Phone screenshot'), ('tablet', 'Tablet screenshot')], max_length=20)),
                ('content_type', models.CharField(max_length=20)),
                ('data', models.BinaryField()),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='checkups.checkup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('checkup', 'kind'), name='one_image_per_kind')],
            },
        ),
    ]
