# Generated by Django 5.2.18 on 2026-10-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkups', '0004_checkupimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkupimage',
            name='kind',
            field=models.CharField(max_length=20),
        ),
    ]
